Repository EddDevv/mg_dev, pull requests merged in 2023-08, with the labels that each got.

#51 feat: added unit test for user
  src/application/controllers/user.controller.ts
  src/domain/users/user.service.spec.ts
  src/domain/users/user.service.ts
Labels: enhancement

#50 feat: added unit test for subscription
  src/domain/subscriptions/subscriptions.service.spec.ts
  src/domain/subscriptions/subscriptions.service.ts
Labels: enhancement

#49 feat: added unit test for service
  src/domain/services/services.service.spec.ts
Labels: enhancement

#48 feat: added unit test for post
  src/domain/posts/post.service.spec.ts
Labels: enhancement

#47 feat: added unit test for portfolio
  src/config/messages/custom.exceptions.ts
  src/domain/portfolio/portfolio.service.spec.ts
  src/domain/portfolio/portfolio.service.ts
Labels: enhancement

#46 feat: added unit test comments
  src/domain/comments/comment.service.spec.ts
Labels: enhancement

#44 feat: added unit test for categories
  src/application/controllers/categories.controller.ts
  src/domain/categories/categories.service.spec.ts
Labels: enhancement

#53 feat: 0.0.9
  package.json
  src/application/controllers/categories.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/auth/auth.response.ts
  src/application/strategies/jwt.strategy.ts
  src/config/messages/custom.exceptions.ts
  src/domain/auth/auth.service.spec.ts
  src/domain/auth/auth.service.ts
  src/domain/business-accounts/business-accounts.service.spec.ts
  src/domain/categories/categories.service.spec.ts
  src/domain/comments/comment.service.spec.ts
  src/domain/portfolio/portfolio.service.spec.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/posts/post.service.spec.ts
  src/domain/services/services.service.spec.ts
  src/domain/subscriptions/subscriptions.service.spec.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.spec.ts
  src/domain/users/user.service.ts
  src/main.ts
Labels: enhancement

#54 feat: create events categories relation
  src/domain/categories/categories.entity.ts
  src/domain/events/events.entity.ts
  src/infrastructure/migrations/1690994084989-create-events-categories-relation.ts
Labels: enhancement

#55 fix: profile item response
  package.json
  src/application/strategies/jwt.strategy.ts
  src/main.ts
Labels: bug

#56 feat: added records
  src/app.module.ts
  src/application/controllers/records.controller.ts
  src/application/dto/events/events.request.ts
  src/application/dto/events/events.response.ts
  src/application/dto/records/records.request.ts
  src/application/dto/records/records.response.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/events/events.entity.ts
  src/domain/records/records.entity.ts
  src/domain/records/records.module.ts
  src/domain/records/records.service.spec.ts
  src/domain/records/records.service.ts
  src/domain/users/user.entity.ts
  src/infrastructure/migrations/1691008655943-test-added-records.ts
  src/infrastructure/repositories/records.repository.ts
Labels: enhancement

#45 Feat: added events
  src/app.module.ts
  src/application/controllers/events.controller.ts
  src/application/controllers/records.controller.ts
  src/application/dto/events/events.request.ts
  src/application/dto/events/events.response.ts
  src/application/dto/records/records.request.ts
  src/application/dto/records/records.response.ts
  src/config/entities.array.ts
  src/config/enums/events.enum.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/categories/categories.entity.ts
  src/domain/events/events.entity.ts
  src/domain/events/events.module.ts
  src/domain/events/events.service.ts
  src/domain/records/records.entity.ts
  src/domain/records/records.module.ts
  src/domain/records/records.service.spec.ts
  src/domain/records/records.service.ts
  src/domain/users/user.entity.ts
  src/infrastructure/migrations/1690824902932-added-events.ts
  src/infrastructure/migrations/1690994084989-create-events-categories-relation.ts
  src/infrastructure/migrations/1691008655943-test-added-records.ts
  src/infrastructure/repositories/events.repository.ts
  src/infrastructure/repositories/records.repository.ts
Labels: enhancement

#60 feat: V0.0.11
  nest-cli.json
  package.json
  src/app.module.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/events.controller.ts
  src/application/controllers/records.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/comments/comments.request.ts
  src/application/dto/events/events.request.ts
  src/application/dto/events/events.response.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/records/records.request.ts
  src/application/dto/records/records.response.ts
  src/application/dto/services/services.request.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/config/entities.array.ts
  src/config/enums/events.enum.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.entity.ts
  src/domain/categories/categories.service.ts
  src/domain/events/events.entity.ts
  src/domain/events/events.module.ts
  src/domain/events/events.service.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/posts/post.service.ts
  src/domain/records/records.entity.ts
  src/domain/records/records.module.ts
  src/domain/records/records.service.spec.ts
  src/domain/records/records.service.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.entity.ts
  src/domain/users/user.service.ts
  src/i18n/en/system.json
  src/i18n/ru/system.json
  src/infrastructure/migrations/1690824902932-added-events.ts
  src/infrastructure/migrations/1690994084989-create-events-categories-relation.ts
  src/infrastructure/migrations/1691008655943-test-added-records.ts
  src/infrastructure/repositories/events.repository.ts
  src/infrastructure/repositories/records.repository.ts
  src/main.ts
Labels: enhancement

#61 Feat: added events functional
  package.json
  src/application/controllers/events.controller.ts
  src/application/dto/events/events.request.ts
  src/application/dto/events/events.response.ts
  src/domain/events/events.entity.ts
  src/domain/events/events.service.ts
  src/infrastructure/migrations/1691514613346-added-events-func.ts
  src/infrastructure/repositories/events.repository.ts
  src/main.ts
Labels: bug, enhancement

#66 feat: added records on events
  package.json
  src/application/controllers/events.controller.ts
  src/application/controllers/records.controller.ts
  src/application/dto/events/events.request.ts
  src/config/messages/custom.exceptions.ts
  src/domain/events/events.entity.ts
  src/domain/events/events.module.ts
  src/domain/events/events.service.ts
  src/domain/records/records.module.ts
  src/domain/records/records.service.spec.ts
  src/domain/records/records.service.ts
  src/infrastructure/migrations/1691682894526-added-relation-records.ts
  src/main.ts
Labels: enhancement

#65 Fix: fixed datetime format
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/events/events.request.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/records/records.request.ts
  src/application/dto/services/services.request.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
Labels: bug, documentation

#67 feat: 0.0.14
  package.json
  src/application/controllers/events.controller.ts
  src/application/controllers/records.controller.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/events/events.request.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/records/records.request.ts
  src/application/dto/services/services.request.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/config/messages/custom.exceptions.ts
  src/domain/events/events.entity.ts
  src/domain/events/events.module.ts
  src/domain/events/events.service.ts
  src/domain/records/records.module.ts
  src/domain/records/records.service.spec.ts
  src/domain/records/records.service.ts
  src/infrastructure/migrations/1691682894526-added-relation-records.ts
  src/main.ts
Labels: enhancement

#68 feat: 0.0.15
  package-lock.json
  package.json
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/portfolio.controller.ts
  src/application/controllers/services.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/auth/auth.request.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/comments/comments.response.ts
  src/application/dto/events/events.response.ts
  src/application/dto/likes/likes.response.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/posts/posts.response.ts
  src/application/dto/records/records.request.ts
  src/application/dto/services/services.request.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/application/dto/users/users.response.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.service.ts
  src/domain/comments/comment.service.ts
  src/domain/events/events.service.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/posts/post.service.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/main.ts
Labels: enhancement

#71 Feat: pagination
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/services.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/events/events.request.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/services/services.request.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/config/pagination.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.service.ts
  src/domain/events/events.service.ts
  src/domain/posts/post.service.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
Labels: documentation, enhancement

#70 fix: createdAt on date of birthday
  src/application/dto/users/users.request.ts
Labels: bug, documentation

#73 feat: 0.0.17
  package.json
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/services.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/events/events.request.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/services/services.request.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/config/pagination.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.service.ts
  src/domain/events/events.service.ts
  src/domain/posts/post.service.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/main.ts
Labels: enhancement

#64 feat: i18n integration in services
  src/application/controllers/app.controller.ts
  src/application/controllers/auth.controller.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/comments.controller.ts
  src/application/controllers/events.controller.ts
  src/application/controllers/portfolio.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/controllers/records.controller.ts
  src/application/controllers/services.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/services/services.request.ts
  src/application/dto/services/services.response.ts
  src/application/strategies/jwt.strategy.ts
  src/domain/auth/auth.service.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.service.ts
  src/domain/comments/comment.service.ts
  src/domain/events/events.service.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/posts/post.service.ts
  src/domain/records/records.service.ts
  src/domain/services/services.entity.ts
  src/domain/services/services.module.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/i18n/en/exceptions.json
  src/i18n/ru/exceptions.json
  src/infrastructure/migrations/1691676912098-updating-services.ts
Labels: enhancement

#75 feat: added new exceptions
  src/i18n/en/exceptions.json
  src/i18n/ru/exceptions.json
Labels: enhancement

#76 feat: 0.1.0
  package-lock.json
  package.json
  src/application/controllers/app.controller.ts
  src/application/controllers/auth.controller.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/comments.controller.ts
  src/application/controllers/events.controller.ts
  src/application/controllers/portfolio.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/controllers/records.controller.ts
  src/application/controllers/services.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/auth/auth.request.ts
  src/application/dto/likes/likes.request.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/posts/posts.response.ts
  src/application/dto/services/services.request.ts
  src/application/dto/services/services.response.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/application/strategies/jwt.strategy.ts
  src/config/messages/custom.exceptions.ts
  src/domain/auth/auth.service.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.service.ts
  src/domain/comments/comment.service.ts
  src/domain/events/events.service.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/posts/post.entity.ts
  src/domain/posts/post.service.ts
  src/domain/records/records.service.ts
  src/domain/services/services.entity.ts
  src/domain/services/services.module.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/i18n/en/exceptions.json
  src/i18n/ru/exceptions.json
  src/infrastructure/migrations/1691676912098-updating-services.ts
  src/infrastructure/repositories/users.repository.ts
  src/main.ts
Labels: documentation, enhancement, rework

#77 Fix bugs 0 1 0
  src/application/controllers/comments.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/likes/likes.response.ts
  src/domain/comments/comment.service.ts
  src/domain/posts/post.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
Labels: bug

#78 Develop
  package.json
  src/application/controllers/comments.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/likes/likes.response.ts
  src/domain/comments/comment.service.ts
  src/domain/posts/post.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/main.ts
Labels: bug
