Repository EddDevv/mg_dev, pull requests merged in 2023-07, with the labels that each got.

#4 Migrate to typeorm
  package.json
  src/app.module.ts
  src/application/controllers/auth.controller.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/locations.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/auth/auth.request.ts
  src/application/dto/auth/auth.response.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/business-accounts/business-accounts.response.ts
  src/application/dto/users/users.request.ts
  src/application/dto/users/users.response.ts
  src/config/basic-repository.interface.ts
  src/config/basic.entity.ts
  src/config/entities.array.ts
  src/domain/auth/auth.module.ts
  src/domain/auth/auth.service.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.module.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/locations/location.entity.ts
  src/domain/locations/locations.module.ts
  src/domain/locations/locations.service.ts
  src/domain/social/social-links.entity.ts
  src/domain/users/user.entity.ts
  src/domain/users/user.module.ts
  src/domain/users/user.service.ts
  src/infrastructure/dataSourceOptions.ts
  src/infrastructure/repositories/business-accounts.repository.ts
  src/infrastructure/repositories/locations.repository.ts
  src/infrastructure/repositories/users.repository.ts
  yarn.lock
Labels: rework

#5 Swagger doc
  src/application/controllers/auth.controller.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/user.controller.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/auth/auth.service.ts
  src/domain/business-accounts/business-accounts.service.ts
Labels: documentation

#8 feat: added cors
  src/main.ts
Labels: enhancement

#7 Fix: VDS start
  .development.env
  .env.example
  .gitignore
  .production.env
  README.md
  package-lock.json
  package.json
  src/infrastructure/dataSourceOptions.ts
  src/infrastructure/migrations/1689173423798-init.ts
  yarn.lock
Labels: enhancement

#10 Version 0.0.2
  .development.env
  .env.example
  .gitignore
  .production.env
  README.md
  package-lock.json
  package.json
  src/application/controllers/auth.controller.ts
  src/application/dto/auth/auth.request.ts
  src/application/guards/jwt.guard.ts
  src/application/guards/pass-match.pipe.ts
  src/application/strategies/jwt.strategy.ts
  src/domain/auth/auth.module.ts
  src/domain/auth/auth.service.ts
  src/domain/users/user.entity.ts
  src/infrastructure/dataSourceOptions.ts
  src/infrastructure/migrations/1689173423798-init.ts
  src/infrastructure/migrations/1689271402124-registration-fix.ts
  src/main.ts
  yarn.lock
Labels: enhancement

#11 fix: guard check
  src/application/guards/jwt.guard.ts
  src/config/user-request.interface.ts
  src/main.ts
Labels: bug

#12 feat: added subscriptions
  package-lock.json
  src/app.module.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/subscriptions/subscriptions.response.ts
  src/application/dto/users/users.response.ts
  src/config/entities.array.ts
  src/domain/subscriptions/subscriptions.entity.ts
  src/domain/subscriptions/subscriptions.module.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.entity.ts
  src/infrastructure/migrations/1689346039892-subscriptions-add.ts
  src/infrastructure/repositories/subscriptions.repository.ts
Labels: documentation, enhancement

#15 Feat: Profile route
  package-lock.json
  package.json
  src/application/controllers/app.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/guards/auth.guard.ts
  src/application/guards/jwt.guard.ts
  src/application/strategies/jwt.strategy.ts
  src/config/user-request.interface.ts
  src/domain/auth/auth.module.ts
  src/domain/auth/auth.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.module.ts
Labels: documentation, enhancement

#16 Feat: class for responses
  src/application/controllers/app.controller.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/auth/auth.response.ts
  src/application/dto/business-accounts/business-accounts.response.ts
  src/application/dto/subscriptions/subscriptions.response.ts
  src/application/dto/users/users.response.ts
  src/config/basic.response.ts
  src/config/user-request.interface.ts
  src/domain/auth/auth.service.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/subscriptions/subscriptions.entity.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.entity.ts
  src/domain/users/user.service.ts
  src/infrastructure/repositories/business-accounts.repository.ts
Labels: documentation

#17 Fix: register and last name
  src/application/dto/auth/auth.request.ts
  src/application/dto/users/users.response.ts
  src/domain/auth/auth.service.ts
  src/domain/users/user.entity.ts
  src/infrastructure/migrations/1689429310192-user-fistName.ts
Labels: documentation, rework

#13 V0.0.3
  package-lock.json
  package.json
  src/app.module.ts
  src/application/controllers/app.controller.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/auth/auth.request.ts
  src/application/dto/auth/auth.response.ts
  src/application/dto/business-accounts/business-accounts.response.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/subscriptions/subscriptions.response.ts
  src/application/dto/users/users.response.ts
  src/application/guards/auth.guard.ts
  src/application/guards/jwt.guard.ts
  src/application/strategies/jwt.strategy.ts
  src/config/basic.response.ts
  src/config/entities.array.ts
  src/config/user-request.interface.ts
  src/domain/auth/auth.module.ts
  src/domain/auth/auth.service.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/subscriptions/subscriptions.entity.ts
  src/domain/subscriptions/subscriptions.module.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.entity.ts
  src/domain/users/user.module.ts
  src/domain/users/user.service.ts
  src/infrastructure/migrations/1689346039892-subscriptions-add.ts
  src/infrastructure/migrations/1689429310192-user-fistName.ts
  src/infrastructure/repositories/business-accounts.repository.ts
  src/infrastructure/repositories/subscriptions.repository.ts
  src/main.ts
Labels: documentation, enhancement, rework

#20 Fix: responses messages
  src/application/controllers/app.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/config/messages/response.messages.ts
Labels: documentation

#18 Fix: refresh token
  src/application/controllers/auth.controller.ts
  src/application/dto/auth/auth.request.ts
  src/application/dto/auth/auth.response.ts
  src/domain/auth/auth.service.ts
Labels: bug, documentation

#22 Update: V0.0.4
  package.json
  src/application/controllers/app.controller.ts
  src/application/controllers/auth.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/dto/auth/auth.request.ts
  src/application/dto/auth/auth.response.ts
  src/config/messages/response.messages.ts
  src/domain/auth/auth.service.ts
  src/main.ts
Labels: enhancement

#23 Feat: add user update
  src/application/controllers/user.controller.ts
  src/application/dto/users/users.request.ts
  src/application/dto/users/users.response.ts
  src/config/messages/custom.exceptions.ts
  src/domain/users/user.entity.ts
  src/domain/users/user.service.ts
Labels: documentation, enhancement

#24 Update: V0.0.5
  package.json
  src/application/controllers/user.controller.ts
  src/application/dto/users/users.request.ts
  src/application/dto/users/users.response.ts
  src/config/messages/custom.exceptions.ts
  src/domain/users/user.entity.ts
  src/domain/users/user.service.ts
  src/main.ts
Labels: enhancement

#25 feat: added comments functional
  src/app.module.ts
  src/application/controllers/comments.controller.ts
  src/application/dto/comments/comments.request.ts
  src/application/dto/comments/comments.response.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/posts/posts.response.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/comments/comment.entity.ts
  src/domain/comments/comment.module.ts
  src/domain/comments/comment.service.ts
  src/domain/posts/post.entity.ts
  src/domain/posts/post.module.ts
  src/domain/users/user.entity.ts
  src/infrastructure/migrations/1689687153978-added-comments.ts
  src/infrastructure/repositories/comments.repository.ts
Labels: documentation, enhancement

#14 feat: added Posts functional
  package-lock.json
  package.json
  src/app.module.ts
  src/application/controllers/comments.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/dto/comments/comments.request.ts
  src/application/dto/comments/comments.response.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/posts/posts.response.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.module.ts
  src/domain/comments/comment.entity.ts
  src/domain/comments/comment.module.ts
  src/domain/comments/comment.service.ts
  src/domain/posts/post.entity.ts
  src/domain/posts/post.module.ts
  src/domain/posts/post.service.ts
  src/domain/users/user.entity.ts
  src/infrastructure/migrations/1689343687696-create-user-business-relation.ts
  src/infrastructure/migrations/1689677820634-added-posts.ts
  src/infrastructure/migrations/1689687153978-added-comments.ts
  src/infrastructure/repositories/comments.repository.ts
  src/infrastructure/repositories/posts.repository.ts
Labels: enhancement

#28 fix: added nullable request
  src/application/dto/users/users.request.ts
  src/domain/users/user.entity.ts
  src/infrastructure/dataSourceOptions.ts
Labels: bug

#29 Update: 0.0.6
  package-lock.json
  package.json
  src/app.module.ts
  src/application/controllers/comments.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/dto/comments/comments.request.ts
  src/application/dto/comments/comments.response.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/posts/posts.response.ts
  src/application/dto/users/users.request.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.module.ts
  src/domain/comments/comment.entity.ts
  src/domain/comments/comment.module.ts
  src/domain/comments/comment.service.ts
  src/domain/posts/post.entity.ts
  src/domain/posts/post.module.ts
  src/domain/posts/post.service.ts
  src/domain/users/user.entity.ts
  src/infrastructure/dataSourceOptions.ts
  src/infrastructure/migrations/1689343687696-create-user-business-relation.ts
  src/infrastructure/migrations/1689677820634-added-posts.ts
  src/infrastructure/migrations/1689687153978-added-comments.ts
  src/infrastructure/repositories/comments.repository.ts
  src/infrastructure/repositories/posts.repository.ts
  src/main.ts
Labels: enhancement

#31 Fix: softRemove on softDelete
  src/config/basic-repository.interface.ts
  src/domain/comments/comment.service.ts
  src/domain/posts/post.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/infrastructure/repositories/business-accounts.repository.ts
  src/infrastructure/repositories/comments.repository.ts
  src/infrastructure/repositories/locations.repository.ts
  src/infrastructure/repositories/posts.repository.ts
  src/infrastructure/repositories/subscriptions.repository.ts
  src/infrastructure/repositories/users.repository.ts
Labels: bug, rework

#30 fix: changed registrationNumber and constructor BusinessAccountEntity
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/infrastructure/migrations/1689687811316-registrationNumber-fix.ts
Labels: bug

#33 Feat: like system
  src/application/controllers/comments.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/dto/likes/likes.request.ts
  src/application/dto/likes/likes.response.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/posts/posts.response.ts
  src/config/entities.array.ts
  src/config/messages/response.messages.ts
  src/domain/comments/comment.entity.ts
  src/domain/comments/comment.module.ts
  src/domain/comments/comment.service.ts
  src/domain/likes/likes.entity.ts
  src/domain/likes/likes.module.ts
  src/domain/posts/post.entity.ts
  src/domain/posts/post.module.ts
  src/domain/posts/post.service.ts
  src/infrastructure/migrations/1689936944975-added-like-system.ts
  src/infrastructure/repositories/likes.repository.ts
Labels: documentation, enhancement

#35 Feat added portfolio
  src/app.module.ts
  src/application/controllers/portfolio.controller.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/portfolio/portfolio.response.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.module.ts
  src/domain/portfolio/portfolio.entity.ts
  src/domain/portfolio/portfolio.module.ts
  src/domain/portfolio/portfolio.service.ts
  src/infrastructure/migrations/1689859574760-create-portfolio.ts
  src/infrastructure/repositories/portfolio.repository.ts
Labels: enhancement

#34 V0.0.7
  package.json
  src/app.module.ts
  src/application/controllers/comments.controller.ts
  src/application/controllers/portfolio.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/dto/likes/likes.request.ts
  src/application/dto/likes/likes.response.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/portfolio/portfolio.response.ts
  src/application/dto/posts/posts.request.ts
  src/application/dto/posts/posts.response.ts
  src/application/dto/users/users.response.ts
  src/config/basic-repository.interface.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/business-accounts/business-account.entity.ts
  src/domain/business-accounts/business-accounts.module.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/comments/comment.entity.ts
  src/domain/comments/comment.module.ts
  src/domain/comments/comment.service.ts
  src/domain/likes/likes.entity.ts
  src/domain/likes/likes.module.ts
  src/domain/portfolio/portfolio.entity.ts
  src/domain/portfolio/portfolio.module.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/posts/post.entity.ts
  src/domain/posts/post.module.ts
  src/domain/posts/post.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.entity.ts
  src/domain/users/user.service.ts
  src/infrastructure/migrations/1689687811316-registrationNumber-fix.ts
  src/infrastructure/migrations/1689772708923-added-posts-views.ts
  src/infrastructure/migrations/1689859574760-create-portfolio.ts
  src/infrastructure/migrations/1689936944975-added-like-system.ts
  src/infrastructure/repositories/business-accounts.repository.ts
  src/infrastructure/repositories/comments.repository.ts
  src/infrastructure/repositories/likes.repository.ts
  src/infrastructure/repositories/locations.repository.ts
  src/infrastructure/repositories/portfolio.repository.ts
  src/infrastructure/repositories/posts.repository.ts
  src/infrastructure/repositories/subscriptions.repository.ts
  src/infrastructure/repositories/users.repository.ts
  src/main.ts
Labels: enhancement

#38 feat: added services
  src/app.module.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/services.controller.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/categories/categories.response.ts
  src/application/dto/services/services.request.ts
  src/application/dto/services/services.response.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/categories/categories.entity.ts
  src/domain/categories/categories.module.ts
  src/domain/categories/categories.service.ts
  src/domain/services/services.entity.ts
  src/domain/services/services.module.ts
  src/domain/services/services.service.ts
  src/infrastructure/migrations/1690295024384-create-services.ts
  src/infrastructure/repositories/services.repository.ts
Labels: enhancement

#39 Feat added category
  src/app.module.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/services.controller.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/categories/categories.response.ts
  src/application/dto/services/services.request.ts
  src/application/dto/services/services.response.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/categories/categories.entity.ts
  src/domain/categories/categories.module.ts
  src/domain/categories/categories.service.ts
  src/domain/services/services.entity.ts
  src/domain/services/services.module.ts
  src/domain/services/services.service.ts
  src/infrastructure/migrations/1690124371330-create-categories.ts
  src/infrastructure/migrations/1690295024384-create-services.ts
  src/infrastructure/repositories/categories.repository.ts
  src/infrastructure/repositories/services.repository.ts
Labels: enhancement

#41 feat: added category and services in portfolio
  src/application/dto/categories/categories.request.ts
  src/application/dto/categories/categories.response.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/portfolio/portfolio.response.ts
  src/application/dto/services/services.request.ts
  src/application/dto/services/services.response.ts
  src/config/messages/custom.exceptions.ts
  src/domain/categories/categories.entity.ts
  src/domain/portfolio/portfolio.entity.ts
  src/domain/portfolio/portfolio.module.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/services/services.entity.ts
  src/domain/services/services.module.ts
  src/domain/services/services.service.ts
  src/infrastructure/migrations/1690486456648-added-category-and-services-in-portfolio.ts
Labels: enhancement

#36 fix: added createdAt to User response
  src/application/dto/users/users.response.ts
Labels: documentation

#37 feat: added redoc
  package-lock.json
  package.json
  src/main.ts
Labels: documentation, rework

#40 feat: in GET Param is replaced by Query
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/comments.controller.ts
  src/application/controllers/portfolio.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/controllers/services.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/categories/categories.response.ts
  src/application/dto/comments/comments.request.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/portfolio/portfolio.response.ts
  src/application/dto/services/services.request.ts
  src/application/dto/services/services.response.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/config/messages/custom.exceptions.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.entity.ts
  src/domain/comments/comment.service.ts
  src/domain/portfolio/portfolio.entity.ts
  src/domain/portfolio/portfolio.module.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/services/services.entity.ts
  src/domain/services/services.module.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/infrastructure/migrations/1690486456648-added-category-and-services-in-portfolio.ts
Labels: rework

#42 V0.0.8
  package-lock.json
  package.json
  src/app.module.ts
  src/application/controllers/business-accounts.controller.ts
  src/application/controllers/categories.controller.ts
  src/application/controllers/comments.controller.ts
  src/application/controllers/portfolio.controller.ts
  src/application/controllers/posts.controller.ts
  src/application/controllers/services.controller.ts
  src/application/controllers/subscriptions.controller.ts
  src/application/controllers/user.controller.ts
  src/application/dto/business-accounts/business-accounts.request.ts
  src/application/dto/categories/categories.request.ts
  src/application/dto/categories/categories.response.ts
  src/application/dto/comments/comments.request.ts
  src/application/dto/portfolio/portfolio.request.ts
  src/application/dto/portfolio/portfolio.response.ts
  src/application/dto/services/services.request.ts
  src/application/dto/services/services.response.ts
  src/application/dto/subscriptions/subscriptions.request.ts
  src/application/dto/users/users.request.ts
  src/application/dto/users/users.response.ts
  src/config/entities.array.ts
  src/config/messages/custom.exceptions.ts
  src/config/messages/response.messages.ts
  src/domain/business-accounts/business-accounts.service.ts
  src/domain/categories/categories.entity.ts
  src/domain/categories/categories.module.ts
  src/domain/categories/categories.service.ts
  src/domain/comments/comment.service.ts
  src/domain/portfolio/portfolio.entity.ts
  src/domain/portfolio/portfolio.module.ts
  src/domain/portfolio/portfolio.service.ts
  src/domain/services/services.entity.ts
  src/domain/services/services.module.ts
  src/domain/services/services.service.ts
  src/domain/subscriptions/subscriptions.service.ts
  src/domain/users/user.service.ts
  src/infrastructure/migrations/1690124371330-create-categories.ts
  src/infrastructure/migrations/1690295024384-create-services.ts
  src/infrastructure/migrations/1690486456648-added-category-and-services-in-portfolio.ts
  src/infrastructure/repositories/categories.repository.ts
  src/infrastructure/repositories/services.repository.ts
  src/main.ts
Labels: enhancement
